### ISSUE TITLE
Webcam / iSight

### ISSUE THREAD

**Issue by carhensi** [x-t/x220-mojave-efi#1]
Thanks for sharing your EFI 👍 So far works like a charm with 10.14.5. I'm just having some graphic glitches and system freezes during wakeup. I also had do create a system serial Number and UUID with Clover to make iCloud work. 

Is your Webcam working? I tried various things including `AnyiSightCam.kext` which makes the cam to show up as "Build-in-iSight". Sadly no success so far.

**Comment by x-t** [comment]
> graphic glitches

Yeah, those happen, I looked into it and the only option for the HD3000 is to go back to Sierra :/

> system freezes during wakeup

Maybe perhaps 
```
$ sudo pmset -a hibernatemode 0
```
would help? I've never experienced that.

> Is your Webcam working?

My model doesn't have a webcam, sorry.

**Comment by carhensi** [comment]
Thanks for the feedback :)
